spring.application.name=love

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_booking
spring.datasource.username=postgres
spring.datasource.password=password 
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.transaction.coordinator_class=jta
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossStandAloneJtaPlatform

# JAAS user store
security.jaas.users-xml=classpath:jaas-users.xml

# Logging
logging.level.root=INFO
logging.level.ru.itmo.love=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.arjuna=INFO
