lib.dir=lib
junit=${lib.dir}/junit-4.13.2.jar
hamcrest=${lib.dir}/hamcrest-core-1.3.jar
contrib=${lib.dir}/ant-contrib-1.0b3.jar
jakarta=${lib.dir}/jakarta.persistence-api-3.1.0.jar
src.dir=src/main
main.dir=${src.dir}/java/org/ruslan
web.dir=${src.dir}/webapp
resources.dir=${src.dir}/resources
native2ascii.resources=${resources.dir}/native2ascii

ant.dir=ant
build.dir=${ant.dir}/build
build.dir.lib=${build.dir}/WEB-INF/lib
build.web.xml=${build.dir}/WEB-INF/web.xml
classes.dir=${build.dir}/WEB-INF/classes

test.classes.dir=${build.dir}/test/classes
test.dir=src/test/java

compile.version=1

report.dir=./report
junit.report.dir=${build.dir}/junit-report
svn.dir=./svn
build=./build
classes=${build}/classes
report.name=test.xml

svn.repo.url=file:///Users/ruslankara-oglanov/Desktop/opi/lab3/svn
dir.versions=versions
output.zip=previous_versions.zip
